name: EC7xx
run-name: GoGoGo 🚀
on: 
  workflow_dispatch:
  workflow_call:

jobs:
  # LuatOS固件编译
  EC718P_LuatOS:
    runs-on: ubuntu-latest
    # needs: "EC7xx_basic"
    strategy:
      fail-fast: false
      matrix:
        csdk_project:
          - luatos
        csdk_chip:
          - ec718u
          - ec718p
          - ec716e
          - ec718hm
    steps:
      - name: 克隆 LuatOS 代码库
        run:  git clone -b v2001.release.pc https://gitee.com/openLuat/LuatOS.git
      - name: 克隆 ec7xx-csdk 代码库
        run: | 
          git clone --depth=1 https://github.com/ghosthgy/luatos-soc-2024.git
          sudo chmod +x luatos-soc-2024/PLAT/tools/fcelf
      - name: 下载GCC工具链
        run: |
          mkdir /home/runner/toolchains
          wget -q -O /home/runner/toolchains/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 https://github.com/wendal/xmake-docker/releases/download/dev-gcc/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
      - name: 初始化工具链
        run: |
          sudo add-apt-repository ppa:xmake-io/xmake -y
          sudo apt update -y
          sudo apt-get update -y && sudo apt-get install -y gcc make g++ wget curl p7zip-full 
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt-get install -y lib32z1 libc6:i386 libgcc1:i386 libstdc++5:i386 libstdc++6:i386
          sudo apt-get install -y xmake
          xmake update
          # curl -fsSL https://xmake.io/shget.text | bash -s v2.8.9
          xmake g --pkg_searchdirs=/home/runner/toolchains
      - name: 构建指定项目
        run: |
          cd luatos-soc-2024/project/${{matrix.csdk_project}} 
          xmake f --chip_target=${{matrix.csdk_chip}} -y
          xmake -y --root

  EC7xx:
    runs-on: ubuntu-latest
    # needs: "EC7xx_basic"
    strategy:
      fail-fast: false
      matrix:
        csdk_chip:
          - ec718u
          - ec718p
          - ec716s
    steps:
      - name: 克隆 LuatOS 代码库
        run:  git clone -b v2001.release.pc https://gitee.com/openLuat/LuatOS.git
      - name: 克隆 ec7xx-csdk 代码库
        run: | 
          git clone --depth=1 https://github.com/ghosthgy/luatos-soc-2024.git
          sudo chmod +x luatos-soc-2024/PLAT/tools/fcelf
      - name: 下载GCC工具链
        run: |
          mkdir /home/runner/toolchains
          wget -q -O /home/runner/toolchains/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2 https://github.com/wendal/xmake-docker/releases/download/dev-gcc/gcc-arm-none-eabi-10-2020-q4-major-x86_64-linux.tar.bz2
      - name: 初始化工具链
        run: |
          sudo add-apt-repository ppa:xmake-io/xmake -y
          sudo apt update -y
          sudo apt-get update -y && sudo apt-get install -y gcc make g++ wget curl p7zip-full python3
          sudo dpkg --add-architecture i386 && sudo apt update
          sudo apt-get install -y lib32z1 libc6:i386 libgcc1:i386 libstdc++5:i386 libstdc++6:i386
          sudo apt-get install -y xmake
          xmake update
          # curl -fsSL https://xmake.io/shget.text | bash -s v2.8.9
          xmake g --pkg_searchdirs=/home/runner/toolchains
      - name: 构建指定项目
        run: |
          cd luatos-soc-2024/ci/
          python3 ci_build.py ${{matrix.csdk_chip}}
